number = int(input("Write a number: "))

print(f"{number}x1 = {number*1}")
print(f"{number}x2 = {number*2}")
print(f"{number}x3 = {number*3}")
print(f"{number}x4 = {number*4}")
print(f"{number}x5 = {number*5}")
print(f"{number}x6 = {number*6}")
print(f"{number}x8 = {number*7}")
print(f"{number}x9 = {number*9}")
print(f"{number}x10 = {number*10}")
